# LOD1 候选街区汇总与统一指标计算

本 notebook 是 LOD1 指标计算的统一入口，替代原先分散在 `block_metric_check.ipynb` 和 `block_summary_metrics.ipynb` 中的主流程。

数据从各城市 `block.<city>_blocks` 和 `lod1.<city>_buildings_lod1` 读取，写入独立的 `summary.lod1_candidate_blocks`。唯一候选条件是街区至少关联一栋 LOD1 建筑，即 `lod1_building_count >= 1`；建筑数量按已匹配且具有 `block_id` 的建筑记录统计，几何无效只会使相关测度保持 `NULL`。本轮不依据 BCR、街区几何有效性、指标空值、旧筛选标记或 Isolation Forest 排除记录。原 `summary.lod1_valid_blocks` 不参与写入。

In [1]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
from dotenv import load_dotenv

import metrics_calculator as met_cal
import utils_z

In [2]:
LOD1_CITIES = [
    "hamburg", "sanfrancisco", "amsterdam", "dresden",
    "berlin", "rotterdam", "luxembourg", "chicago",
    "boston", "washington", "newyork", "portland",
    "tokyo", "sapporo", "osaka", "kanazawa",
    "toronto", "vienna", "winnipeg", "zurich",
    "bologna", "paris", "lyon", "marseille",
]
TARGET_TABLE = "summary.lod1_candidate_blocks"
MIN_FOOTPRINT_AREA_M2_FOR_COMPLEXITY = 1.0

# 所有写入默认关闭。只读预检通过后，按编号逐项打开并运行对应单元。
APPLY_1_SOURCE_BLOCK_METRICS = True
APPLY_2_CREATE_CANDIDATE_TABLE = True
APPLY_3_REBUILD_CANDIDATE_TABLE = True
APPLY_4_PREPARE_BUILDING_MEASUREMENTS = True
APPLY_5_COMPUTE_ALL_CANDIDATE_METRICS = True

print(f"城市数：{len(LOD1_CITIES)}；目标表：{TARGET_TABLE}")

城市数：24；目标表：summary.lod1_candidate_blocks

In [3]:
load_dotenv()
required_env = ["DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT"]
missing_env = [name for name in required_env if not os.getenv(name)]
if missing_env:
    raise RuntimeError("缺少数据库环境变量：" + ", ".join(missing_env))

conn = utils_z.get_conn(
    os.getenv("DB_NAME"), os.getenv("DB_USER"),
    os.getenv("DB_PASSWORD"), os.getenv("DB_HOST"),
    os.getenv("DB_PORT"),
)
print("数据库连接成功")

数据库连接成功

## 0. 只读预检

确认 24 个城市的 block/LOD1 建筑表存在，几何统一存储为 EPSG:4326，并且 `summary.city_name_map` 中具有可用的 `lod1_metric_srid`。

In [ ]:
metric_plan = met_cal.validate_lod1_metric_environment(
    conn, cities=LOD1_CITIES, require_summary=False
)
print(f"预检通过：{len(metric_plan)} 个城市")
for item in metric_plan:
    print(f"  {item['city_code']}: {item['source_srid']} → EPSG:{item['metric_srid']}")

## 1. 重算分城市 block 表的基础指标

对完整分城市 block 表重算 `area_m2`、`elongation`、`compactness`、`geom_is_valid`、`lod1_building_count` 和 `lod1_bcr`。`elongation` 为城市测度 CRS 中最小旋转外接矩形的短边/长边。该步骤不读取或修改旧 `is_valid_lod1`。首次运行会把旧值保存到 `summary.a_fix_r02_lod1_block_metrics_backup`。

In [ ]:
if APPLY_1_SOURCE_BLOCK_METRICS:
    source_result = met_cal.compute_lod1_source_block_metrics(
        conn, cities=LOD1_CITIES, verbose=True
    )
    print(f"分城市基础指标完成：{len(source_result)} 个城市")
else:
    print("未写库：APPLY_1_SOURCE_BLOCK_METRICS=False")

## 2. 创建独立候选汇总表

仅创建 `summary.lod1_candidate_blocks` 及索引；不会创建、清空或更新 `summary.lod1_valid_blocks`。

In [ ]:
if APPLY_2_CREATE_CANDIDATE_TABLE:
    met_cal.ensure_lod1_metric_table(conn, target_table=TARGET_TABLE)
    print(f"候选表已确认存在：{TARGET_TABLE}")
else:
    print("未写库：APPLY_2_CREATE_CANDIDATE_TABLE=False")

## 3. 从分城市 block 表重建候选集

唯一 WHERE 条件为 `lod1_building_count >= 1`。候选表已有数据会先保存到 `summary.a_fix_r03_lod1_candidate_backup`，再在同一事务中清空和重建。

In [ ]:
if APPLY_3_REBUILD_CANDIDATE_TABLE:
    candidate_result = met_cal.rebuild_lod1_candidate_table(
        conn, cities=LOD1_CITIES, target_table=TARGET_TABLE,
        confirm=True, verbose=True,
    )
    print(f"候选街区总数：{candidate_result['total']:,}")
else:
    print("未写库：APPLY_3_REBUILD_CANDIDATE_TABLE=False")

In [7]:
with conn.cursor() as cur:
    cur.execute("SELECT to_regclass(%s);", (TARGET_TABLE,))
    candidate_exists = cur.fetchone()[0] is not None

if candidate_exists:
    df_candidate_count = pd.read_sql_query(
        f"SELECT city, COUNT(*) AS candidate_count FROM {TARGET_TABLE} GROUP BY city ORDER BY city;",
        conn,
    )
    display(df_candidate_count)
    print(f"候选表当前总数：{int(df_candidate_count['candidate_count'].sum()):,}")
else:
    print(f"候选表尚不存在：{TARGET_TABLE}")

C:\Users\94017\AppData\Local\Temp\ipykernel_48832\4117660990.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_candidate_count = pd.read_sql_query(

               city  candidate_count
0         Amsterdam             3118
1            Berlin             9191
2           Bologna             1204
3            Boston             4015
4           Chicago            16898
5           Dresden             2268
6           Hamburg             5157
7          Kanazawa            10052
8        Luxembourg              498
9              Lyon             1591
10        Marseille             2536
11         New York             2743
12            Osaka            23443
13            Paris             3614
14         Portland             9377
15        Rotterdam             2793
16    San Francisco             4732
17          Sapporo            29955
18            Tokyo            58668
19          Toronto            10107
20           Vienna             6002
21  Washington D.C.             4564
22         Winnipeg             5414
23           Zurich             1479

候选表当前总数：219,419

## 4. 准备通用建筑测度

先检查每个城市的缺失量：已有建筑面积和周长保持不变，仅用 `geography` 补算 `NULL`；已有正层数保留，只对层数缺失或非正、且高度有效的记录按 `height/3` 估算。没有待补值的城市自动跳过，城市特例数据修复不放在本步骤。

In [4]:
if APPLY_4_PREPARE_BUILDING_MEASUREMENTS:
    building_result = met_cal.prepare_lod1_building_measurements(
        conn, cities=LOD1_CITIES,
        area_perimeter_mode="missing",
        fill_missing_floor_count=True,
        verbose=True,
    )
    print(f"建筑通用测度准备完成：{len(building_result)} 个城市")
else:
    print("未写库：APPLY_4_PREPARE_BUILDING_MEASUREMENTS=False")

[hamburg] 已完整，跳过
[sanfrancisco] 已完整，跳过
[amsterdam] 已完整，跳过
[dresden] 已完整，跳过
[berlin] 已完整，跳过
[rotterdam] 已完整，跳过
[luxembourg] 已完整，跳过
[chicago] 已完整，跳过
[boston] 已完整，跳过
[washington] 已完整，跳过
[newyork] 已完整，跳过
[portland] 已完整，跳过
[tokyo] 已完整，跳过
[sapporo] 已完整，跳过
[osaka] 已完整，跳过
[kanazawa] 已完整，跳过
[toronto] 已完整，跳过
[vienna] 已完整，跳过
[winnipeg] 已完整，跳过
[zurich] 已完整，跳过
[bologna] 已完整，跳过
[paris] 已完整，跳过
[lyon] 已完整，跳过
[marseille] 已完整，跳过
建筑通用测度准备完成：24 个城市

## 5. 计算候选集全部指标

依次计算密度、高度、体量、街区与建筑形态、轴向朝向和最近邻距离。欧氏平面计算使用各城市 `lod1_metric_srid`；无法计算的记录继续保持 `NULL`。

In [5]:
if APPLY_5_COMPUTE_ALL_CANDIDATE_METRICS:
    metric_result = met_cal.compute_all_lod1_metrics(
        conn, cities=LOD1_CITIES, target_table=TARGET_TABLE,
        min_footprint_area_m2=MIN_FOOTPRINT_AREA_M2_FOR_COMPLEXITY,
        verbose=True,
    )
    print("候选集全部指标计算完成")
    print(metric_result)
else:
    print("未写库：APPLY_5_COMPUTE_ALL_CANDIDATE_METRICS=False")

[hamburg] 密度/高度/体量：5,157 个街区
[sanfrancisco] 密度/高度/体量：4,732 个街区
[amsterdam] 密度/高度/体量：3,118 个街区
[dresden] 密度/高度/体量：2,268 个街区
[berlin] 密度/高度/体量：9,191 个街区
[rotterdam] 密度/高度/体量：2,793 个街区
[luxembourg] 密度/高度/体量：498 个街区
[chicago] 密度/高度/体量：16,898 个街区
[boston] 密度/高度/体量：4,015 个街区
[washington] 密度/高度/体量：4,564 个街区
[newyork] 密度/高度/体量：2,743 个街区
[portland] 密度/高度/体量：9,377 个街区
[tokyo] 密度/高度/体量：58,668 个街区
[sapporo] 密度/高度/体量：29,955 个街区
[osaka] 密度/高度/体量：23,443 个街区
[kanazawa] 密度/高度/体量：10,052 个街区
[toronto] 密度/高度/体量：10,107 个街区
[vienna] 密度/高度/体量：6,002 个街区
[winnipeg] 密度/高度/体量：5,414 个街区
[zurich] 密度/高度/体量：1,479 个街区
[bologna] 密度/高度/体量：1,204 个街区
[paris] 密度/高度/体量：3,614 个街区
[lyon] 密度/高度/体量：1,591 个街区
[marseille] 密度/高度/体量：2,536 个街区
[hamburg] 形态：街区 5,157，建筑聚合 5,157，EPSG:25832
[sanfrancisco] 形态：街区 4,732，建筑聚合 4,732，EPSG:32610
[amsterdam] 形态：街区 3,118，建筑聚合 3,118，EPSG:28992
[dresden] 形态：街区 2,268，建筑聚合 2,268，EPSG:25833
[berlin] 形态：街区 9,191，建筑聚合 9,191，EPSG:25833
[rotterdam] 形态：街区 2,793，建筑聚合 2,793，EPSG:28992
[luxembourg] 形态：街区 498，建筑聚合 498，EPSG:2169
[chicago] 形态：街区 16,898，建筑聚合 16,897，EPSG:32616
[boston] 形态：街区 4,015，建筑聚合 4,015，EPSG:32619
[washington] 形态：街区 4,564，建筑聚合 4,564，EPSG:32618
[newyork] 形态：街区 2,743，建筑聚合 2,743，EPSG:32618
[portland] 形态：街区 9,377，建筑聚合 9,377，EPSG:32610
[tokyo] 形态：街区 58,668，建筑聚合 58,668，EPSG:6677
[sapporo] 形态：街区 29,955，建筑聚合 29,955，EPSG:6680
[osaka] 形态：街区 23,443，建筑聚合 23,443，EPSG:6674
[kanazawa] 形态：街区 10,052，建筑聚合 10,052，EPSG:6675
[toronto] 形态：街区 10,107，建筑聚合 10,107，EPSG:32617
[vienna] 形态：街区 6,002，建筑聚合 6,002，EPSG:31256
[winnipeg] 形态：街区 5,414，建筑聚合 5,414，EPSG:32614
[zurich] 形态：街区 1,479，建筑聚合 1,479，EPSG:2056
[bologna] 形态：街区 1,204，建筑聚合 1,204，EPSG:32632
[paris] 形态：街区 3,614，建筑聚合 3,613，EPSG:2154
[lyon] 形态：街区 1,591，建筑聚合 1,591，EPSG:2154
[marseille] 形态：街区 2,536，建筑聚合 2,536，EPSG:2154
[hamburg] 朝向：5,157 个街区，EPSG:25832
[sanfrancisco] 朝向：4,732 个街区，EPSG:32610
[amsterdam] 朝向：3,118 个街区，EPSG:28992
[dresden] 朝向：2,268 个街区，EPSG:25833
[berlin] 朝向：9,191 个街区，EPSG:25833
[rotterdam] 朝向：2,793 个街区，EPSG:28992
[luxembourg] 朝向：498 个街区，EPSG:2169
[chicago] 朝向：16,897 个街区，EPSG:32616
[boston] 朝向：4,015 个街区，EPSG:32619
[washington] 朝向：4,564 个街区，EPSG:32618
[newyork] 朝向：2,743 个街区，EPSG:32618
[portland] 朝向：9,377 个街区，EPSG:32610
[tokyo] 朝向：58,668 个街区，EPSG:6677
[sapporo] 朝向：29,955 个街区，EPSG:6680
[osaka] 朝向：23,443 个街区，EPSG:6674
[kanazawa] 朝向：10,052 个街区，EPSG:6675
[toronto] 朝向：10,107 个街区，EPSG:32617
[vienna] 朝向：6,002 个街区，EPSG:31256
[winnipeg] 朝向：5,414 个街区，EPSG:32614
[zurich] 朝向：1,479 个街区，EPSG:2056
[bologna] 朝向：1,204 个街区，EPSG:32632
[paris] 朝向：3,613 个街区，EPSG:2154
[lyon] 朝向：1,591 个街区，EPSG:2154
[marseille] 朝向：2,536 个街区，EPSG:2154

NN Distance:   0%|          | 0/24 [00:00<?, ?city/s]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(
NN Distance:   4%|▍         | 1/24 [00:03<01:22,  3.59s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[hamburg] 最近邻：5,020 个街区，EPSG:25832

NN Distance:   8%|▊         | 2/24 [00:05<01:01,  2.82s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[sanfrancisco] 最近邻：4,560 个街区，EPSG:32610

NN Distance:  12%|█▎        | 3/24 [00:07<00:47,  2.28s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[amsterdam] 最近邻：2,925 个街区，EPSG:28992

NN Distance:  17%|█▋        | 4/24 [00:08<00:38,  1.95s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[dresden] 最近邻：2,216 个街区，EPSG:25833

NN Distance:  21%|██        | 5/24 [00:15<01:07,  3.57s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[berlin] 最近邻：9,018 个街区，EPSG:25833

NN Distance:  25%|██▌       | 6/24 [00:16<00:51,  2.86s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[rotterdam] 最近邻：2,585 个街区，EPSG:28992

NN Distance:  29%|██▉       | 7/24 [00:17<00:34,  2.03s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[luxembourg] 最近邻：458 个街区，EPSG:2169

NN Distance:  33%|███▎      | 8/24 [00:32<01:39,  6.24s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[chicago] 最近邻：16,494 个街区，EPSG:32616

NN Distance:  38%|███▊      | 9/24 [00:34<01:13,  4.88s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[boston] 最近邻：3,779 个街区，EPSG:32619

NN Distance:  42%|████▏     | 10/24 [00:36<00:56,  4.04s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[washington] 最近邻：4,351 个街区，EPSG:32618

NN Distance:  46%|████▌     | 11/24 [00:37<00:40,  3.14s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[newyork] 最近邻：2,448 个街区，EPSG:32618

NN Distance:  50%|█████     | 12/24 [00:41<00:42,  3.52s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[portland] 最近邻：9,008 个街区，EPSG:32610

NN Distance:  54%|█████▍    | 13/24 [01:13<02:11, 11.98s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[tokyo] 最近邻：57,867 个街区，EPSG:6677

NN Distance:  58%|█████▊    | 14/24 [01:24<01:56, 11.67s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[sapporo] 最近邻：29,636 个街区，EPSG:6680

NN Distance:  62%|██████▎   | 15/24 [01:33<01:38, 10.98s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[osaka] 最近邻：23,126 个街区，EPSG:6674

NN Distance:  67%|██████▋   | 16/24 [01:37<01:10,  8.84s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[kanazawa] 最近邻：9,841 个街区，EPSG:6675

NN Distance:  71%|███████   | 17/24 [01:44<00:56,  8.12s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[toronto] 最近邻：9,989 个街区，EPSG:32617

NN Distance:  75%|███████▌  | 18/24 [01:48<00:42,  7.12s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[vienna] 最近邻：5,879 个街区，EPSG:31256

NN Distance:  79%|███████▉  | 19/24 [01:51<00:28,  5.78s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[winnipeg] 最近邻：5,341 个街区，EPSG:32614

NN Distance:  83%|████████▎ | 20/24 [01:52<00:17,  4.31s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[zurich] 最近邻：1,430 个街区，EPSG:2056

NN Distance:  88%|████████▊ | 21/24 [01:53<00:09,  3.24s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[bologna] 最近邻：1,177 个街区，EPSG:32632

NN Distance:  92%|█████████▏| 22/24 [01:54<00:05,  2.70s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[paris] 最近邻：3,312 个街区，EPSG:2154

NN Distance:  96%|█████████▌| 23/24 [01:55<00:02,  2.16s/city]e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1029: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

[lyon] 最近邻：1,443 个街区，EPSG:2154

NN Distance: 100%|██████████| 24/24 [01:56<00:00,  4.87s/city]

[marseille] 最近邻：2,396 个街区，EPSG:2154
候选集全部指标计算完成
{'nn_distance': {'total_blocks': 219419, 'computed': 214299, 'still_null': 5120, 'global_avg_m': 12.825951565134064, 'min_m': 0.0, 'max_m': 1337.6354923206397, 'updated_this_run': 214299}}

## 6. 完整性检查（只读）

这里统计各城市每项指标的非空数量，不把空值自动判为无效。

In [8]:
if candidate_exists:
    df_completeness = met_cal.summarize_lod1_metric_completeness(
        conn, target_table=TARGET_TABLE
    )
    display(df_completeness)
    print(f"完整性检查记录数：{int(df_completeness['total'].sum()):,}")
else:
    print("候选表不存在，暂不执行完整性检查")

e:\0_code\block-gml-casebase\casebase\metrics_calculator.py:1119: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(f"""

,city,total,area_m2,elongation,compactness,lod1_building_count,bcr,convexity,rectangularity,far,...,total_volume,avg_volume,avg_footprint,footprint_cv,avg_complexity,avg_rectangularity,avg_convexity,avg_orientation,orientation_entropy,avg_nn_distance
0,Amsterdam,3118,3118,3118,3118,3118,3118,3118,3118,3118,...,3118,3118,3118,2925,3117,3118,3118,3118,3118,2925
1,Berlin,9191,9191,9191,9191,9191,9191,9191,9191,9191,...,9191,9191,9191,9018,9191,9191,9191,9191,9191,9018
2,Bologna,1204,1204,1204,1204,1204,1204,1204,1204,1204,...,1204,1204,1204,1177,1204,1204,1204,1204,1204,1177
3,Boston,4015,4015,4015,4015,4015,4015,4015,4015,4015,...,4015,4015,4015,3779,4015,4015,4015,4015,4015,3779
4,Chicago,16898,16898,16898,16898,16898,16897,16898,16898,16897,...,16897,16897,16897,16494,16897,16897,16897,16897,16897,16494
5,Dresden,2268,2268,2268,2268,2268,2268,2268,2268,2268,...,2268,2268,2268,2216,2268,2268,2268,2268,2268,2216
6,Hamburg,5157,5157,5157,5157,5157,5157,5157,5157,5157,...,5157,5157,5157,5020,5157,5157,5157,5157,5157,5020
7,Kanazawa,10052,10052,10052,10052,10052,10052,10052,10052,10052,...,10052,10052,10052,9841,10052,10052,10052,10052,10052,9841
8,Luxembourg,498,498,498,498,498,498,498,498,498,...,498,498,498,458,498,498,498,498,498,458
9,Lyon,1591,1591,1591,1591,1591,1591,1591,1591,1591,...,1591,1591,1591,1443,1591,1591,1591,1591,1591,1443
10,Marseille,2536,2536,2536,2536,2536,2536,2536,2536,2536,...,2536,2536,2536,2396,2536,2536,2536,2536,2536,2396
11,New York,2743,2743,2743,2743,2743,2743,2743,2743,2743,...,2743,2743,2743,2448,2743,2743,2743,2743,2743,2448
12,Osaka,23443,23443,23443,23443,23443,23443,23443,23443,23443,...,23443,23443,23443,23126,23443,23443,23443,23443,23443,23126
13,Paris,3614,3614,3614,3614,3614,3614,3614,3614,3614,...,3614,3614,3614,3312,3613,3613,3613,3613,3613,3312
14,Portland,9377,9377,9377,9377,9377,9377,9377,9377,9377,...,9377,9377,9377,9008,9377,9377,9377,9377,9377,9008
15,Rotterdam,2793,2793,2793,2793,2793,2793,2793,2793,2793,...,2793,2793,2793,2585,2793,2793,2793,2793,2793,2585
16,San Francisco,4732,4732,4732,4732,4732,4732,4732,4732,4732,...,4732,4732,4732,4560,4732,4732,4732,4732,4732,4560
17,Sapporo,29955,29955,29955,29955,29955,29955,29955,29955,29955,...,29955,29955,29955,29636,29955,29955,29955,29955,29955,29636
18,Tokyo,58668,58668,58668,58668,58668,58668,58668,58668,58668,...,58668,58668,58668,57867,58668,58668,58668,58668,58668,57867
19,Toronto,10107,10107,10107,10107,10107,10107,10107,10107,10107,...,10107,10107,10107,9989,10107,10107,10107,10107,10107,9989
20,Vienna,6002,6002,6002,6002,6002,6002,6002,6002,6002,...,6002,6002,6002,5879,6002,6002,6002,6002,6002,5879
21,Washington D.C.,4564,4564,4564,4564,4564,4564,4564,4564,4564,...,4564,4564,4564,4351,4564,4564,4564,4564,4564,4351
22,Winnipeg,5414,5414,5414,5414,5414,5414,5414,5414,5414,...,5414,5414,5414,5341,5414,5414,5414,5414,5414,5341
23,Zurich,1479,1479,1479,1479,1479,1479,1479,1479,1479,...,1479,1479,1479,1430,1478,1479,1479,1479,1479,1430

完整性检查记录数：219,419

In [ ]:
# 全部检查完成后再手动运行。
if 'conn' in globals() and conn is not None and not conn.closed:
    conn.close()
    print("数据库连接已关闭")